### ISSUE TITLE
Some cosmetic items display no details under Slot Customization and cannot be altered if equipped.

### ISSUE THREAD

**Issue by AdamJacobson** [Adspartan/For_the_Drip#1]
For some cosmetic items, their individual parts are not visible in the Slot Customization section of the Drip menu. Users cannot disable them from being displayed or change whether or not they are customized with different materials.

Here are some examples:

Aetus MK II Flak Helmet - Gloamus Camo
![image](https://github.com/Adspartan/For_the_Drip/assets/7927980/2920940b-7471-46d5-8fe6-709a5e355f89)

Atoman Pattern Combat Helmet With Rebreather
![image](https://github.com/Adspartan/For_the_Drip/assets/7927980/13180eb7-5a98-4984-b0d2-d9b72c31578d)

Cari Brone's Vox Set
![image](https://github.com/Adspartan/For_the_Drip/assets/7927980/28ce2ae5-4b2d-4eed-8fbb-068199438cdd)

These are only 3 of several I have encountered across multiple different classes.

**Comment by Adspartan** [comment]
Those items don't have any attachments, which is what can be individually customized. You can still customize them though.
