### ISSUE TITLE
consistent crash

### ISSUE THREAD

**Issue by SorenHayes** [Adspartan/For_the_Drip#2]
anytime i attempt to open the operative menu (or the change operative menu) with a FTD headgear applied the game instantly crashes. It only occurs with the headgears and ive had no issues with any other aspect of the mod but it is quite disappointing.
 Ive attempted to:
 1. uninstall and reinstall (the release asset and the archive asset, separately incase that matters) 
 2. change drive locations
 3. launch the game with FTD as the only mod to rule out other mods being problematic
 4. install an older version of the mod
 5. delete FTD settings in AppData
 6. launch the game manually instead of through vortex 
 
 I'm actually completely out of potential fixes atp
 
![Screenshot 2024-10-15 215831](https://github.com/user-attachments/assets/64c26f14-2127-458d-a72e-c514dc24480f)

**Comment by SorenHayes** [comment]
i went back and installed the v.0.10.0 version and the mod works perfectly fine without crashing anymore so if anyone else has this same issue that is your fix!

**Comment by Adspartan** [comment]
Fixed in 9ae99e1a5
